name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies using npm install
      - name: Install dependencies
        run: npm install
        working-directory: daniely

      # Step 4: Build the project
      - name: Build the project
        run: npm run build
        working-directory: daniely

      # Step 5: Configure Git for Deployment
      - name: Set up Git for GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        working-directory: daniely

      # Step 6: Deploy to GitHub Pages using deploy-ci script
      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: daniely